#write a program to input the eight numbers from the user and display all the unique number once 
s = set()
n = input("enter nob 1: ")
s.add(int(n))
n = input("enter nob 2: ")
s.add(int(n))
n = input("enter nob 3: ")
s.add(int(n))
n = input("enter nob 4: ")
s.add(int(n))
n = input("enter nob 5: ")
s.add(int(n))
n = input("enter nob 6: ")
s.add(int(n))
n = input("enter nob 7: ")
s.add(int(n))
n = input("enter nob 8: ")
s.add(int(n))
print(s)