# write a program to store the list of 7 friuts given by the user
fruits =[]
f1 = input("\tenter the fruit name\t : ")
fruits.append(f1)
f2 = input("enter the fruit name  ")
fruits.append(f2)
f3 = input("enter the fruit name  ")
fruits.append(f3)
f4 = input("enter the fruit name  ")
fruits.append(f4)
f5 = input("enter the fruit name  ")
fruits.append(f5)
f6 = input("enter the fruit name  ")
fruits.append(f6)
f7 = input("enter the fruit name  ")
fruits.append(f7)
print(fruits)